# Generated by Django 5.0.8 on 2025-11-01 05:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=255)),
                ('custom_product_type', models.CharField(blank=True, max_length=255)),
                ('volume_range', models.CharField(max_length=100)),
                ('timeline', models.CharField(max_length=100)),
                ('has_formulation', models.CharField(max_length=50)),
                ('branding_requirements', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('hear_about_us', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('quoted', 'Quote Sent'), ('negotiating', 'In Negotiation'), ('converted', 'Converted to Client'), ('declined', 'Declined')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for sales team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('quote_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('meeting', 'Meeting'), ('quote_sent', 'Quote Sent'), ('sample_sent', 'Sample Sent'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField()),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='quotes.quoterequest')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['-created_at'], name='quotes_quot_created_51e95a_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['status'], name='quotes_quot_status_cead77_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['email'], name='quotes_quot_email_f07574_idx'),
        ),
    ]
