# Generated by Django 5.0.8 on 2025-11-01 05:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('shipping_address', models.TextField()),
                ('product_categories', models.CharField(help_text='Comma-separated list of requested categories (e.g., facial care, hair care)', max_length=500)),
                ('specific_products', models.TextField(blank=True, help_text='Specific products or formulations of interest')),
                ('intended_use', models.CharField(choices=[('testing', 'Product Testing'), ('market_research', 'Market Research'), ('evaluation', 'Manufacturing Evaluation'), ('other', 'Other')], max_length=50)),
                ('business_type', models.CharField(blank=True, help_text='e.g., Retailer, Distributor, Brand Owner', max_length=100)),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('preparing', 'Preparing Samples'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('declined', 'Declined')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample Request',
                'verbose_name_plural': 'Sample Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='quotes_samp_created_403afc_idx'), models.Index(fields=['status'], name='quotes_samp_status_4c5be2_idx'), models.Index(fields=['email'], name='quotes_samp_email_ac4290_idx')],
            },
        ),
    ]
