# Generated by Django 5.2.5 on 2025-09-01 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('smtp', 'SMTP'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('ses', 'Amazon SES'), ('postmark', 'Postmark')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('configuration', models.JSONField(default=dict, help_text='Provider-specific configuration')),
                ('daily_limit', models.PositiveIntegerField(default=1000)),
                ('hourly_limit', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('twilio', 'Twilio'), ('nexmo', 'Vonage (Nexmo)'), ('aws_sns', 'AWS SNS'), ('clicksend', 'ClickSend')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('configuration', models.JSONField(default=dict, help_text='Provider-specific configuration')),
                ('daily_limit', models.PositiveIntegerField(default=100)),
                ('hourly_limit', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('send_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('tracking_url', models.URLField(blank=True)),
                ('send_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_marketing', models.BooleanField(default=True)),
                ('email_order_updates', models.BooleanField(default=True)),
                ('email_price_alerts', models.BooleanField(default=True)),
                ('email_stock_alerts', models.BooleanField(default=True)),
                ('sms_order_updates', models.BooleanField(default=False)),
                ('sms_delivery_updates', models.BooleanField(default=False)),
                ('push_order_updates', models.BooleanField(default=True)),
                ('push_price_alerts', models.BooleanField(default=True)),
                ('push_marketing', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('password_reset', 'Password Reset'), ('account_verification', 'Account Verification'), ('price_drop', 'Price Drop Alert'), ('back_in_stock', 'Back in Stock'), ('low_stock_admin', 'Low Stock Alert (Admin)'), ('newsletter', 'Newsletter'), ('promotional', 'Promotional'), ('system_maintenance', 'System Maintenance')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=200)),
                ('html_template', models.TextField(blank=True)),
                ('text_template', models.TextField(blank=True)),
                ('sms_template', models.TextField(blank=True, help_text='SMS message template (160 chars max)')),
                ('push_title_template', models.CharField(blank=True, max_length=100)),
                ('push_body_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['notification_type', 'channel'], name='notificatio_notific_1005f2_idx')],
                'unique_together': {('notification_type', 'channel')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate'),
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('bulk', 'Bulk'), ('retry', 'Retry')], default='immediate', max_length=20)),
                ('priority_score', models.IntegerField(default=0)),
                ('is_processing', models.BooleanField(default=False)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='notifications.notification')),
            ],
            options={
                'ordering': ['-priority_score', 'created_at'],
                'indexes': [models.Index(fields=['queue_type', 'is_processing'], name='notificatio_queue_t_b652e8_idx'), models.Index(fields=['priority_score', 'created_at'], name='notificatio_priorit_4ccc07_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'send_at'], name='notificatio_status_73a2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['template', 'status'], name='notificatio_templat_1a9c31_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'send_at'], name='notificatio_priorit_900255_idx'),
        ),
    ]
