# Generated by Django 5.2.3 on 2025-07-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Thailand', max_length=100),
            preserve_default=False,
        ),
    ]
