# Generated by Django 5.2.5 on 2025-09-01 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_auto_20250901_0645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_when_added', models.DecimalField(blank=True, decimal_places=2, help_text='Price when item was added to wishlist', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('back_in_stock', 'Back in Stock'), ('low_stock', 'Low Stock Alert'), ('wishlist_shared', 'Wishlist Shared'), ('item_purchased', 'Item Purchased by Someone')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlistitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=False)),
                ('privacy_level', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('public', 'Public')], default='private', max_length=10)),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('share_url', models.URLField(blank=True)),
                ('share_message', models.TextField(blank=True, help_text='Message to show when sharing wishlist')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wishlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_settings', to='wishlist.wishlist')),
            ],
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['wishlist', 'added_at'], name='wishlist_wi_wishlis_b99dca_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['added_at'], name='wishlist_wi_added_a_1c2b5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product')},
        ),
        migrations.AddIndex(
            model_name='wishlistnotification',
            index=models.Index(fields=['user', 'is_read'], name='wishlist_wi_user_id_8e3584_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistnotification',
            index=models.Index(fields=['notification_type'], name='wishlist_wi_notific_c54e37_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistnotification',
            index=models.Index(fields=['created_at'], name='wishlist_wi_created_9ef130_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistshare',
            index=models.Index(fields=['share_token'], name='wishlist_wi_share_t_884e44_idx'),
        ),
    ]
