# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview_reviewhelpful_and_more'),
    ]

    operations = [
        # Remove review models from products app
        migrations.DeleteModel(
            name='ReviewHelpful',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]